spring.application.name=api-gateway

server:
  port: 8080 # El Gateway suele usar el puerto principal

spring:
  cloud:
    gateway:
      routes:
        # Redirigir a Microservicio de Clientes
        - id: ms-cliente
          uri: http://localhost:8081 # El puerto donde levantaste ms-cliente
          predicates:
            - Path=/clientes/**

        # Redirigir a Microservicio de Ventas
        - id: ms-ventas
          uri: http://localhost:8082 # El puerto donde levantaste ms-ventas
          predicates:
            - Path=/ventas/**

        # Redirigir a Microservicio de Categorías
        - id: ms-categoria
          uri: http://localhost:8083 # El puerto donde levantaste ms-categoria
          predicates:
            - Path=/categorias/**